version: "3.5"
services:
  app:
    image: rce-app
    container_name: "rce-app"
    working_dir: "/app"
    build:
      context: "../"
      dockerfile: "docker/app/Dockerfile"
      target: "dev"
    volumes:
      - "../src/:/app/"
    networks: 
      rce:
        aliases:
          - "app"
  proxy:
    depends_on: ["app"]
    image: rce-proxy
    container_name: "rce-proxy"
    working_dir: "/app"
    build:
      context: "../"
      dockerfile: "docker/nginx/Dockerfile"
    ports:
      - "8022:80"
      - "4443:443"
    volumes:
      - "../src/:/app/"
      - "../docker/nginx/rce.conf:/etc/nginx/conf.d/default.conf"
    networks:
      rce:
        aliases:
          - "proxy"
networks:
  rce:
